name: Deploy to AWS CloudFront

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 14

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [$NODE_VERSION]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: $NODE_VERSION

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to AWS CloudFront
      uses: aws-actions/upload-directory@v1
      with:
        directory: .next
        region: us-west-2
        distribution-id: YOUR_DISTRIBUTION_ID
        wait-for-deployment: true
        
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id  ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
